before_script:
  - chmod +x ./scripts/update-version.sh

services:
  - docker:dind

stages:
  - release

release:
  stage: release
  image: node:16.13.2
  only:
    - /^release$/
  tags: [frontend]
  script:
    - ./scripts/update-version.sh
